name: Publish VS Code Extension

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Install dependencies
        run: npm ci

      - name: Package extension
        run: vsce package

      - name: Publish extension
        run: vsce publish --pat ${{ secrets.VSCE_TOKEN }}
